package com.emfield.visualizer.utils

import android.content.Context
import android.util.Log
import com.emfield.visualizer.data.MagneticFieldData
import kotlinx.coroutines.*
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

/**
 * Simple export manager for building APK
 */
class ExportManager(private val context: Context) {
    
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())
    private val dateFormat = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US)
    
    /**
     * Export data to CSV format
     */
    suspend fun exportToCSV(dataPoints: List<MagneticFieldData>): File? = withContext(Dispatchers.IO) {
        return@withContext try {
            val timestamp = dateFormat.format(Date())
            val fileName = "em_field_data_$timestamp.csv"
            val file = File(context.getExternalFilesDir(null), fileName)
            
            FileWriter(file).use { writer ->
                writer.write("timestamp,pos_x,pos_y,pos_z,field_x,field_y,field_z,magnitude,accuracy\n")
                
                for (point in dataPoints) {
                    writer.write(
                        "${point.timestamp}," +
                        "${point.position.x},${point.position.y},${point.position.z}," +
                        "${point.field.x},${point.field.y},${point.field.z}," +
                        "${point.magnitude()},${point.accuracy}\n"
                    )
                }
            }
            
            Log.i("ExportManager", "Exported ${dataPoints.size} points to CSV: ${file.absolutePath}")
            file
        } catch (e: Exception) {
            Log.e("ExportManager", "Failed to export CSV", e)
            null
        }
    }
    
    /**
     * Export data to JSON format
     */
    suspend fun exportToJSON(dataPoints: List<MagneticFieldData>): File? = withContext(Dispatchers.IO) {
        return@withContext try {
            val timestamp = dateFormat.format(Date())
            val fileName = "em_field_data_$timestamp.json"
            val file = File(context.getExternalFilesDir(null), fileName)
            
            FileWriter(file).use { writer ->
                writer.write("{\n")
                writer.write("  \"metadata\": {\n")
                writer.write("    \"exportTime\": ${System.currentTimeMillis()},\n")
                writer.write("    \"pointCount\": ${dataPoints.size},\n")
                writer.write("    \"version\": \"1.0\"\n")
                writer.write("  },\n")
                writer.write("  \"dataPoints\": [\n")
                
                for ((index, point) in dataPoints.withIndex()) {
                    writer.write("    {\n")
                    writer.write("      \"timestamp\": ${point.timestamp},\n")
                    writer.write("      \"position\": [${point.position.x}, ${point.position.y}, ${point.position.z}],\n")
                    writer.write("      \"field\": [${point.field.x}, ${point.field.y}, ${point.field.z}],\n")
                    writer.write("      \"magnitude\": ${point.magnitude()},\n")
                    writer.write("      \"accuracy\": ${point.accuracy}\n")
                    writer.write("    }")
                    if (index < dataPoints.size - 1) writer.write(",")
                    writer.write("\n")
                }
                
                writer.write("  ]\n")
                writer.write("}\n")
            }
            
            Log.i("ExportManager", "Exported ${dataPoints.size} points to JSON: ${file.absolutePath}")
            file
        } catch (e: Exception) {
            Log.e("ExportManager", "Failed to export JSON", e)
            null
        }
    }
    
    /**
     * Export data to OBJ format
     */
    suspend fun exportToOBJ(dataPoints: List<MagneticFieldData>): File? = withContext(Dispatchers.IO) {
        return@withContext try {
            val timestamp = dateFormat.format(Date())
            val fileName = "em_field_mesh_$timestamp.obj"
            val file = File(context.getExternalFilesDir(null), fileName)
            
            FileWriter(file).use { writer ->
                writer.write("# EM Field Visualization\n")
                writer.write("# Generated by EM Field Visualizer\n")
                writer.write("# Points: ${dataPoints.size}\n\n")
                
                // Write vertices
                for (point in dataPoints) {
                    writer.write("v ${point.position.x} ${point.position.y} ${point.position.z}\n")
                }
                
                writer.write("\n# Field vectors as lines\n")
                for ((index, point) in dataPoints.withIndex()) {
                    val endPoint = point.position + (point.direction() * (point.magnitude() / 100f).coerceIn(0.05f, 0.3f))
                    writer.write("v ${endPoint.x} ${endPoint.y} ${endPoint.z}\n")
                }
                
                writer.write("\n# Lines (field vectors)\n")
                for (i in 1..dataPoints.size) {
                    writer.write("l $i ${dataPoints.size + i}\n")
                }
            }
            
            Log.i("ExportManager", "Exported ${dataPoints.size} points to OBJ: ${file.absolutePath}")
            file
        } catch (e: Exception) {
            Log.e("ExportManager", "Failed to export OBJ", e)
            null
        }
    }
    
    companion object {
        private const val TAG = "ExportManager"
    }
}
